-- 初始版本：创建核心表并初始化系统数据

-- ================== 用户表 ==================
CREATE TABLE IF NOT EXISTS t_user (
    id BIGINT PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    email VARCHAR(128),
    nickname VARCHAR(64),
    status SMALLINT DEFAULT 1,
    is_admin SMALLINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT DEFAULT 0
);

-- ================== RBAC 核心表 ==================
CREATE TABLE IF NOT EXISTS t_role (
    id BIGINT PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(255),
    status SMALLINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT DEFAULT 0
);

-- 权限表仅保留树形层级信息，不存储页面 URL；URL 通过 t_permission_resource 关联到 t_resource
CREATE TABLE IF NOT EXISTS t_permission (
    id BIGINT PRIMARY KEY,
    code VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    parent_id BIGINT,
    status SMALLINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS t_user_role (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS t_role_permission (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_role_permission UNIQUE (role_id, permission_id)
);

-- ================== 资源表 ==================
CREATE TABLE IF NOT EXISTS t_resource (
    id BIGINT PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    type VARCHAR(32) NOT NULL, -- API / PUBLIC / PAGE / LOGIN
    status SMALLINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS t_permission_resource (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    permission_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_permission_resource UNIQUE (permission_id, resource_id)
);

-- ================== 索引 ==================
CREATE INDEX IF NOT EXISTS idx_user_role_user_id ON t_user_role(user_id);
CREATE INDEX IF NOT EXISTS idx_user_role_role_id ON t_user_role(role_id);
CREATE INDEX IF NOT EXISTS idx_role_permission_role_id ON t_role_permission(role_id);
CREATE INDEX IF NOT EXISTS idx_role_permission_permission_id ON t_role_permission(permission_id);
CREATE INDEX IF NOT EXISTS idx_permission_code ON t_permission(code);
CREATE INDEX IF NOT EXISTS idx_permission_parent_id ON t_permission(parent_id);
CREATE INDEX IF NOT EXISTS idx_permission_resource_permission_id ON t_permission_resource(permission_id);
CREATE INDEX IF NOT EXISTS idx_permission_resource_resource_id ON t_permission_resource(resource_id);
CREATE INDEX IF NOT EXISTS idx_resource_code ON t_resource(code);
CREATE INDEX IF NOT EXISTS idx_resource_type ON t_resource(type);

-- ================== 初始化权限树 ==================
INSERT INTO t_permission (id, code, name, parent_id, status)
VALUES (1001, 'system:menu', '系统设置', NULL, 1)
ON CONFLICT (code) DO NOTHING;

INSERT INTO t_permission (id, code, name, parent_id, status)
VALUES (1002, 'user:menu', '用户管理', 1001, 1)
ON CONFLICT (code) DO NOTHING;

-- ================== 初始化角色 ==================
INSERT INTO t_role (id, code, name, description, status)
VALUES
    (1, 'system_admin', '系统管理员', '拥有系统设置与用户管理权限', 1),
    (2, 'super_admin', '超级管理员', '系统内置超级管理员，拥有所有权限且不可删除', 1)
ON CONFLICT (code) DO NOTHING;

-- ================== 初始化资源 ==================
INSERT INTO t_resource (id, code, name, type, status)
VALUES
    -- 认证
    (1, 'POST:/jcloud/api/auth/register', '用户注册', 'PUBLIC', 1),
    (2, 'POST:/jcloud/api/auth/login', '用户登录', 'PUBLIC', 1),
    (3, 'GET:/jcloud/api/auth/me', '当前用户信息', 'LOGIN', 1),

    -- 页面菜单
    (30, '/admin', '系统设置', 'PAGE', 1),
    (31, '/admin/users', '用户管理', 'PAGE', 1),

    -- 用户管理接口
    (10, 'POST:/jcloud/api/users', '新增用户', 'API', 1),
    (11, 'GET:/jcloud/api/users', '用户分页查询', 'API', 1),
    (12, 'GET:/jcloud/api/users/{id}', '查看用户详情', 'API', 1),
    (13, 'GET:/jcloud/api/users/search', '按用户名搜索用户', 'API', 1),
    (14, 'PUT:/jcloud/api/users/{id}/roles', '分配用户角色', 'API', 1),
    (15, 'PUT:/jcloud/api/users/{id}/status', '修改用户状态', 'API', 1),
    (16, 'DELETE:/jcloud/api/users/{id}', '删除用户', 'API', 1),
    (17, 'PUT:/jcloud/api/users/{id}', '编辑用户', 'API', 1),
    (18, 'DELETE:/jcloud/api/users/batch', '批量删除用户', 'API', 1),
    (19, 'PUT:/jcloud/api/users/batch/status', '批量修改用户状态', 'API', 1),

    -- 角色管理接口
    (20, 'GET:/jcloud/api/roles', '角色列表', 'API', 1)
ON CONFLICT (code) DO NOTHING;

-- ================== 资源与权限关联 ==================
INSERT INTO t_permission_resource (permission_id, resource_id)
SELECT p.id, r.id
FROM t_permission p
         CROSS JOIN t_resource r
WHERE (p.code = 'system:menu' AND r.code = '/admin')
   OR (p.code = 'user:menu'
    AND r.code IN (
        '/admin/users',
        'POST:/jcloud/api/users',
        'GET:/jcloud/api/users',
        'GET:/jcloud/api/users/{id}',
        'GET:/jcloud/api/users/search',
        'PUT:/jcloud/api/users/{id}/roles',
        'PUT:/jcloud/api/users/{id}/status',
        'DELETE:/jcloud/api/users/{id}',
        'PUT:/jcloud/api/users/{id}',
        'DELETE:/jcloud/api/users/batch',
        'PUT:/jcloud/api/users/batch/status',
        'GET:/jcloud/api/roles'
    ))
ON CONFLICT (permission_id, resource_id) DO NOTHING;

-- ================== 为角色绑定权限 ==================
INSERT INTO t_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM t_role r
         CROSS JOIN t_permission p
WHERE r.code IN ('system_admin', 'super_admin')
  AND p.code IN ('system:menu', 'user:menu')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- ================== 为已存在的 admin 用户绑定超级管理员角色 ==================
INSERT INTO t_user_role (user_id, role_id)
SELECT u.id, r.id
FROM t_user u
         CROSS JOIN t_role r
WHERE u.username = 'admin'
  AND r.code = 'super_admin'
ON CONFLICT (user_id, role_id) DO NOTHING;
